//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HBS.Data.Entities.TimeTracking.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebMenu
    {
        public WebMenu()
        {
            this.aspnet_Roles = new HashSet<aspnet_Roles>();
        }
    
        public int MenuId { get; set; }
        public string Title { get; set; }
        public string Controller { get; set; }
        public string Action { get; set; }
        public Nullable<int> OrderNumber { get; set; }
    
        public virtual ICollection<aspnet_Roles> aspnet_Roles { get; set; }
    }
}
